### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by eduardoinnorway** [maxfierke/ui-bootstrap-fontawesome#2]
Well, I just followed your instructions, nothing happend, it still shows wrong icons.
Why don't you make a working plunker that shows that this works and how to make it work?

**Comment by maxfierke** [comment]
It's working in production on a handful of apps I've built. Make sure that `ui.bootstrap.fontawesome` is loaded after `ui.bootstrap` in your module dependencies. (Also, make sure you've got the font-awesome CSS loaded).

[Here's a Plnkr](http://plnkr.co/edit/QQh4CHSmuVCN6O9hyRn3)

It has not yet been tested with UI-Bootstrap 0.14.x, so that may be the issue if you're on that.

**Comment by eduardoinnorway** [comment]
I always read the README carefully so all this points are checked. Try Datepicker in your plunker, it does not work because the template still uses the other icons.

**Comment by maxfierke** [comment]
[Updated Plnkr](http://plnkr.co/edit/4g4S6Y2LZFwoEtUiKFe9)

The tests are passing and the Plnkrs are showing working examples using Font-Awesome icons. I don't know what else to tell you.

Again, 0.14.x is not supported yet, as the module names for templates were changed. But you should not have any issues using it with Angular-UI Bootstrap 0.12.x-0.13.x

**Comment by gastonelhordoy** [comment]
Hey guys, just submitted PR #3 which adds the uib prefixes that angular-ui team added in the latests versions of angular-bootstrap.

@maxfierke let me know if you need anything else in order to merge it.

Cheers

**Comment by maxfierke** [comment]
Now supporting the 1.2.x Angular-UI releases. Let me if this doesn't fix your issue.
